name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  specmatic-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Verify Docker is available
        run: docker --version

      - name: Run linter
        env:
          CENTRAL_CONFIG_REPO_TOKEN: ${{ secrets.CENTRAL_CONFIG_REPO_TOKEN }}
        run: |
          docker run --rm -e CENTRAL_CONFIG_REPO_TOKEN \
          -v "./demo/central-config-repo:/usr/src/app" \
          specmatic/enterprise lint openapi.yaml \
          --config-repo-url=https://github.com/specmatic/central-linter-config.git \
          --config=specmatic-linter.yaml \
          --profile=public-api
